config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "public_recipes#index"

  resources :foods, only: [:index, :show, :new, :create, :destroy]
  resources :recipes, only: [:index, :show, :new, :create, :destroy] do
    resources :recipe_foods, only: [:new, :create, :destroy, :update, :edit] 
    resources :shopping_lists, only: [:index, :show]    
  end
  resources :public_recipes, only: [:index]

  devise_scope :user do 
    get '/users/sign_out' => 'devise/sessions#destroy' 
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.is? :admin
      can :manage, :all
    else
      can :manage, Recipe, user_id: user.id
      can :manage, Food, user_id: user.id
      can :manage, Recipe do |recipe|
        recipe.user == user || recipe.public == true || !recipe.user_id?
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipes, through: :recipe_foods
  has_many :recipe_foods, dependent: :destroy

  validates :name, length: { in: 1..250 }, presence: true, allow_blank: false
  validates :measurement_unit, length: { in: 1..250 }, presence: true, allow_blank: false
  validates :price, presence: true, allow_blank: false
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 5, maximum: 5000 }
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  validates :quantity, presence: true
  validates :food_id, presence: true
  validates :recipe_id, presence: true

  belongs_to :recipe
  belongs_to :food
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :foods, dependent: :destroy
  has_many :recipes, dependent: :destroy

  validates :name, presence: true, length: { minimum: 1, maximum: 50 }

  def sum(array)
    sum = 0
    array.each do |number|
      sum += number.quantity * number.food.price
    end
    sum
  end

  ROLES = %i[admin default].freeze

  def is?(requested_role)
    role == requested_role.to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  load_and_authorize_resource
  before_action :set_food, only: %i[show edit update destroy]

  def index
    @foods = current_user.foods
    @food = Food.find_by(id: params[:id])
  end

  def show; end

  def new
    @foods = current_user.foods.includes(:recipes)
  end

  # GET /foods/1/edit
  def edit; end

  def create
    @food = current_user.foods.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to foods_path, notice: 'The ingredients have been added successfully.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @food = Food.find_by(id: params[:id])
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'The ingredient have been deleted successfully.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  def food_params
    params.require(:food).permit(:user_id, :name, :measurement_unit, :price)
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @recipes = Recipe.includes(:recipe_foods, :foods).where(public: true).order('created_at DESC').map do |recipe|
      {
        id: recipe.id,
        recipe_foods: recipe.recipe_foods.map(&:id),
        foods: recipe.foods,
        name: recipe.name,
        user: recipe.user.name,
        description: recipe.description,
        ingredients_amount: recipe.recipe_foods.count,
        ingredients_price: recipe.foods.map(&:price),
        allQuantities: recipe.recipe_foods.map(&:quantity)
      }
    end
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :set_recipe_food, only: %i[show edit update destroy]

  def index
    @recipe_foods = RecipeFood.all
  end

  def show; end

  def new
    @recipe_food = RecipeFood.new
    @recipe = Recipe.find(params[:recipe_id])
    @foods = Food.all
  end

  def edit
    @recipe_food = RecipeFood.find(params[:id])
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.create(recipe_food_params)
    if @recipe_food.save
      flash[:notice] = 'Ingredient added successfully.'
      redirect_to @recipe
    else
      render :new
    end
  end

  def update
    @recipe_food = RecipeFood.find(params[:id])
    if @recipe_food.update(new_params)
      flash[:success] = 'Recipe Food updated successfully.'
    else
      flash[:error] = 'Something went wrong'
    end
    redirect_to recipe_path(@recipe_food.recipe_id)
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])

    @recipe_food.destroy
    flash[:success] = 'Recipe Food deleted successfully.'
    redirect_to recipe_path(@recipe_food.recipe_id)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe_food
    @recipe_food = RecipeFood.find(params[:id])
  end

  def new_params
    params.require(:recipe_food).permit(:quantity, :food_id)
  end

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :food_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  load_and_authorize_resource
  before_action :set_recipe, only: %i[show edit update destroy]

  def index
    @recipes = current_user.recipes
    @recipe = Recipe.find_by(id: params[:id])
  end

  def show; end

  def new
    @recipes = current_user.recipes.includes(:foods)
  end

  # GET /recipes/1/edit
  def edit; end

  def create
    @recipe = current_user.recipes.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe = Recipe.find_by(id: params[:id])
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  def index
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_foods = RecipeFood.all
    @food = Food.all
    @total_price = current_user.sum(@recipe.recipe_foods.includes([:food]))
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name)
  end
end

app/views/foods/index.html.erb
<div class="container-fluid d-flex flex-column align-items-center">
  <h1 class="font-bold text-center mb-4">Ingredients</h1>
  <div>
    <%= link_to "Add ingredient", new_food_path, class:"btn btn-success create" %>
  </div>
  <div class="container-fluid d-flex flex-column align-items">
    <table class="table table-bordered table-striped recipe-table mt-4">
      <thead>
        <tr class="text-center">
          <th scope="col">Ingredient</th>
          <th scope="col">Measurement unit</th>
          <th scope="col">Unit price</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <% @foods.each do |food| %>
        <tbody>
          <tr>
            <td><%= food.name %></td>
            <td><%= food.measurement_unit %></td>
            <td><%= food.price %></td>
            <td class="text-center"><%= button_to "Delete", food_path(id: food.id), method: :delete, class:"btn btn-outline-danger btn-sm" %></td>
          </tr>
        </tbody>
      <% end %>
    </table>
  </div>
</div>

app/views/foods/new.html.erb
<div class="container-fluid d-flex flex-column align-items-center">
  <h2>Add new ingredient</h2>
  <div class="mx-auto">
    <%= form_with model: @food, method: :post, local: true do |form| %>
      <div class="card mt-4">
        <div class="card-body">
          <%= form.hidden_field :user_id, value: current_user.id %>
          <div class="mb-3">
            <%= form.label :name, { class: "form-label" } %><br>
            <%= form.text_field :name, placeholder: 'Name' %>
          </div>
          <div class="mb-3">
            <%= form.label :measurement_unit, { class: "form-label" } %><br>
            <%= form.text_field :measurement_unit, placeholder: 'Measurement unit' %>
          </div>
          <div class="text-field mb-3">
            <%= form.label :price, { class: "form-label" } %><br>
            <%= form.number_field :price, placeholder: 'Price' %>
          </div>
          <div class="text-center mb-2 mt-5">
            <%= form.submit class:"btn btn-success create" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <hr>
  <p class="text-center">Copyright &reg; 2022 <a href="https://github.com/Ewoskyx" class="text-decoration-none">Evren Ersoy</a> and 
    <a href="https://github.com/Hombre2014" class="text-decoration-none">Yuriy Chamkoriyski</a> - All rights reserved
  </p>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar">
  <div class="container">
    <% if current_user %>
      <ul class="navbar-nav w-100 d-flex flex-row justify-content-between bg-light">
        <div class="container-fluid row">
          <li class="nav-item col">
              <%= link_to 'Home', root_path, class: "nav-link" %>
          </li>
          <li class="nav-item col">
              <%= link_to 'Recipes', recipes_path, class: "nav-link" %>
          </li>
          <li class="nav-item col">
            <%= link_to 'Ingredients', foods_path, class: "nav-link" %>
          </li>
          <li class="nav-item col">
            <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        </div>
      </ul>
      <div class="mx-auto">
        <h2 class="fw-bold">Welcome, <%= current_user.name %></h2>
      </div>
    <% else %>
      <ul class="navbar-nav w-100 d-flex flex-row justify-content-between">
        <li class="nav-item">
            <%= link_to 'Home', root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Log in', new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %>
        </li>
      </ul>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipies App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <%= csrf_meta_tags %> <%= csp_meta_tag %>
    <link rel= "stylesheet" href = "https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= render 'layouts/navbar' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/public_recipes/index.html.erb
<section class="container mx-auto mt-2">
  <h3 class="fs-1 lh-lg fw-semibold mt-2 text-center">Public Recipes</h3>
  <div class="public-c">
    <ul class="m-0 p-0">
      <% @recipes.each do |recipe| %>
      <li class="card list-style-none mb-3">
        <div class="card-header fs-4">
          <%= link_to recipe[:name], recipe_path(id: recipe[:id]), { class:
          'text-decoration-none' } %>
        </div>
        <div class="card-body">
          <h5 class="card-title">By: <%= recipe[:user] %></h5>
          <div class="d-flex flex-column float-end">
            <p>Total food items: <%= recipe[:ingredients_amount] %></p>
              <% total_price = 0 %>
            <p>Total price: <% recipe[:allQuantities].each_with_index do |quantity, index| %>
              <% total_price += quantity*recipe[:ingredients_price][index] %>
            <%end%>
            $<%= total_price %>
            </p>
          </div>
        </div>
      </li>
      <% end %>
    </ul>
  </div>
</section>

app/views/recipe_foods/edit.html.erb
<div class="container-fluid d-flex flex-column align-items-center">
  <h2 class="heading mt-3 mb-4 ">Edit recipe's ingredients</h2>
  <div class="mx-auto">
    <%= form_with  model: @recipe_food, url: { action: "update"}, local: true, class:"input-form"  do |f|%>
      <div class="card">
        <div class="card-body">
          <div class="mb-3">
            <%= f.label :Ingredient, class:"form-label" %><br>
            <%= f.select :food_id, current_user.foods.collect {|food| [food.name, food.id]},{ include_blank: true} , class:"form-select" %><br>
          </div>
          <div class="mb-3">
            <%= f.label :quantity, class:"form-label" %><br>
            <%= f.number_field :quantity ,  class:"form-control" , required: true, min:1%><br>
          </div>
          <div class="mb-3 col-sm-8 mx-auto">
            <%= f.submit "Update Recipe", class:"btn btn-primary form-control" %>
          </div>
        </div>
      </div>
    <%end%>
    <div class="form-div mt-5">
      <div class="mb-3 col-sm-4 mx-auto">
        <%=link_to 'Back', foods_path, class:"btn btn-warning form-control" %>
      </div>
    </div>
  </div>
</div>

app/views/recipe_foods/new.html.erb
<div class="container-fluid d-flex flex-column align-items-center">
  <h2 class="heading mt-3 mb-4">Add Ingredient for <%= @recipe.name %> recipe</h2>
  <div class="container d-flex flex-column">
    <%= form_with  model: [@recipe, @recipe.recipe_foods.create], class:"input-form"  do |f|%>
      <div class="form-div d-flex flex-column align-items-center">

        <div class="mb-3 col-sm-4">
          <%= f.label :Ingredient, class:"form-label" %><br>
          <%= f.select :food_id, current_user.foods.collect {|food| [food.name, food.id]},{ include_blank: true} , class:"form-select" %><br>
        </div>

        <div class="mb-3 col-sm-4">
          <%= f.label :quantity, class:"form-label" %><br>
          <%= f.number_field :quantity ,  class:"form-control" , required: true, placeholder: '1',  min: 1%><br>
        </div>

        <div class="mb-3 col-sm-2">
          <%= f.submit "Add", class:"btn btn-success form-control" %>
        </div>
      </div>
    <%end%>
    <div class="form-div back d-flex flex-column align-items-center">
      <div class="mb-3 col-sm-2">
        <%=link_to 'Back', recipe_path(@recipe.id), class:"btn btn-warning form-control"%>
      </div>
    </div>
  </div>
</div>

app/views/recipe_foods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quantity:</strong>
  <%= @recipe_food.quantity %>
</p>

<p>
  <strong>Recipe:</strong>
  <%= @recipe_food.recipe_id %>
</p>

<p>
  <strong>Food:</strong>
  <%= @recipe_food.food_id %>
</p>

<%= link_to 'Edit', edit_recipe_food_path(@recipe_food) %> |
<%= link_to 'Back', recipe_foods_path %>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>
      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :preparation_time, style: "display: block" %>
    <%= form.text_field :preparation_time %>
  </div>

  <div>
    <%= form.label :cooking_time, style: "display: block" %>
    <%= form.text_field :cooking_time %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :public, style: "display: block" %>
    <%= form.check_box :public %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_public.html.erb
<%= form_with model: recipe, url: recipes_path do |form| %>
  <div class="form-check form-switch fs-5 align-self-start">
    <% if !recipe.public %>
      <%= form.check_box :public, role: "switch", id: "flexSwitchCheckDefault", class: "form-check-input" %>
      <%= form.label :public, class: "form-check-label fw-semi-bold", for: "flexSwitchCheckDefault" %>
    <% else %>
      <%= form.check_box :public, role: "switch", id: "flexSwitchCheckChecked", class: "form-check-input" %>
      <%= form.label :public, class: "form-check-label fw-semi-bold", for: "flexSwitchCheckChecked" %>
    <% end %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div class="fs-4 p-3 border border-1 container mt-5 p-2">
  <%= form_with model: @recipe, method: :post, local: true do |f| %>
    <%= f.label :name, "Name", class: " recipe-form form-label fs-6" %>
    <%= f.text_field :name, required: true, class: " recipe-form form-control mb-4" %>
    <%= f.label :description, "Write description", class: " recipe-form form-label fs-5" %>
    <%= f.text_area :description, required: true, class: " recipe-form form-control" %>
    <%= f.label :cooking_time, "Cooking Time", class: " recipe-form form-label fs-5" %>
    <%= f.text_field :cooking_time, class: " recipe-form form-control mb-2" %>
    <%= f.label :preparation_time, "Preparation Time", class: " recipe-form form-label fs-5" %>
    <%= f.text_field :preparation_time, class: " recipe-form form-control mb-2" %>
    <div class="form-check form-switch public">
      <%= f.check_box :public, class:"form-check-input" %>
      <%= f.label :public, "Public", class: " recipe-form form-check-label" %>    
    </div>
    <br>
    <%= f.submit "Add Recipe", class: "btn btn-primary my-5" %>
  <% end %>
</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>
<%= render "form", recipe: @recipe %>
<br>
<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<div class="container-fluid">
  <div class="d-flex flex-column align-items-center width-20 mt-4">
    <%= link_to "Create a Recipe", new_recipe_path, class: "btn btn-success create" %>
  </div>
  <ul class="list-group list-unstyled">
    <% @recipes.each do |r| %>
    <li class="border border-1 border-secondary container mt-5 rounded bio">
      <div class="d-flex p-3">
        <div>
          <%= link_to recipe_path(r.id), id: "recipe_path#{r.id}", class: "text-decoration-none" do %>
          <h5 class="me-5"><%= r.name%></h5>
          <% end %>
          <div>
            <%if can? :destroy, r %> <%= button_to "Delete", recipe_path(r.id),
            method: :delete, class: "btn btn-outline-danger"%> <% end %>
          </div>
        </div>
        <div>
          <p class="ml-5"><%= r.description%></p>
        </div>
      </div>
    </li>
    <% end %>
  </ul>
</div>

app/views/recipes/new.html.erb
<h3 class="text-center" > Create Your Recipe</h3>
<div class="recipe-form">
  <%= render "recipe" %>
</div> 

app/views/recipes/show.html.erb
<div class="container-fluid">
  <div class="border border-3 border-primary container rounded recipe-c mb-5 mt-5">
    <div class="my-3">
      <h2><%= @recipe.name%></h2>
    </div>
    <div>
      <div class="split">
        <div class="d-flex justify-content-between">
          <h5>Preparation time: <%= @recipe.preparation_time %> min </h5>
          <div class="public-btn">
            <% if @recipe.public %>
              <div class="form-check form-switch">
                <input class="form-check-input" type="checkbox" id="flexSwitchCheckChecked" checked>
                <label class="form-check-label" for="flexSwitchCheckChecked">Public</label>
              </div>
            <% end %>
            <% if !@recipe.public %>
              <div class="form-check form-switch">
                <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault">
                <label class="form-check-label" for="flexSwitchCheckDefault"></label>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <div>
        <h5 class="pt-2">Cooking time: <%= @recipe.cooking_time %> min </h5>
        <h5 class="pt-2 pb-4">How to: </h5>
        <p><%= @recipe.description %></p>
      </div>
      <div class="d-flex">
        <% if user_signed_in? %>
          <div class="d-flex w-100 justify-content-between mb-3">
            <%= link_to "Generate Shopping list", recipe_shopping_lists_path(@recipe.id), :class => "btn btn-success btn-gen" %>
            <%= link_to "Add ingredient", new_recipe_recipe_food_path(@recipe) , class: "btn btn-success btn-gen "%>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="container w-90">
    <table class="table table-bordered table-striped recipe-table">
      <thead class="text-center">
        <tr>
          <th scope="col">Ingredient</th>
          <th scope="col">Quantity</th>
          <th scope="col">Value</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        <% @recipe.recipe_foods.each do |food| %>
          <tr>
            <th scope="row"><%= food.food.name %></th>
            <td><%= food.quantity  %> x <%= food.food.measurement_unit %></td>
            <td>$<%= food.food.price * food.quantity %></td>
            <td class="table-btn d-flex flex-row justify-content-between">
              <% if user_signed_in? %>
              <% if can? :destroy, @recipe %>
                <%=button_to "Delete", recipe_recipe_food_path(recipe_id: @recipe.id, id: food.id), method: :delete, class:"btn btn-outline-danger btn-sm"%>
                <%=link_to "Modify", edit_recipe_recipe_food_path(recipe_id: @recipe.id, id: food.id), class:"btn btn-outline-primary btn-sm"%>
              <%end%>
              <%end%>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/shopping_lists/index.html.erb
<% if user_signed_in? %>
  <h1 class="text-center mb-5">Shopping List for recipe <%= @recipe.name %></h1>

  <div class="d-flex flex-row justify-content-evenly mb-5">
    <h3>Amount of ingredients to buy: <%= @recipe.recipe_foods.length %> </h3>
    <h3>Total price: $<%= @total_price %> </h3>
  </div>

  <div class="container w-90">
    <table class="table table-bordered table-striped recipe-table">
      <thead>
          <tr>
          <th scope="col">Ingredient</th>
          <th scope="col">Quantity</th>
          <th scope="col">Price</th>
          </tr>
      </thead>
      <tbody>
        <% @recipe.recipe_foods.each do |r| %>
          <% if @food.include?(r.food) %>
            <tr>
              <th scope="row"><%= r.food.name %></th>
              <td><%= r.quantity %> x <%= r.food.measurement_unit %></td>
              <td>$<%= r.food.price * r.quantity %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/users/index.html.erb
<h1 class="text-center">My recipes</h1>